import { PromptCard1, PromptCard2, PromptCard3, PromptCard4, } from "../asset/images";

export const CardList = [
    {
        image: PromptCard1,
        title: "ArtCrypto",
        text: "Cyber Kangaroo In space, sci-fi style, purple colors",
    },
    {
        image: PromptCard2,
        title: "ArtCrypto",
        text: "Cyber Kangaroo In space, sci-fi style, purple colors",
    },
    {
        image: PromptCard3,
        title: "ArtCrypto",
        text: "Cyber Kangaroo In space, sci-fi style, purple colors",
    },
    {
        image: PromptCard4,
        title: "ArtCrypto",
        text: "Cyber Kangaroo In space, sci-fi style, purple colors",
    },
];
export const FeaturesList = [
    {
        heading: "Plug-and-Play Generation for",
        heading2: "NFT Creators",
        text: "Unlike other AI NFT generators, Cryptoverse NFT platform doesn’t require you to have extensive skills in coding and blockchain. The generator is designed to offer you a real plug-and-play experience, allowing anyone to create NFT art.",
    },
    {
        heading: "Create as many Collectibles",
        heading2: "as You Wish",
        text: "You can create single pieces or mint an entire NFT collection. The simple no-code approach of Cryptoverse unique NFTs frees your time to focus on the fun and creative aspects of your NFT generation process.",
    },
    {
        heading: "Generating Unique AI NFTs",
        heading2: "for Multiple Blockchains",
        text: "While many AI NFT generators support one or two blockchains, Cryptoverse AI Generator supports virtually all major blockchains, including Ethereum, BSC Testnet, BNB Chain, opBNB, Tron, Polygon, Avalanche, and others.",
    },
    {
        heading: "Flexible Pricing",
        heading2: "Model",
        text: "Cryptoverse NFT Generator offers you a chance to generate single NFTs for free, or large NFT collection of up to 10,000 for freemium or low cost. Furthermore, our generator offers you a chance to launch one hundred custom NFTs at once for free.",
    },
];
export const QuestionList = [
    {
        heading: "What chains are supported?",
        text: "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire",
    },
    {
        heading: "How many NFTs can be generated at once?",
        text: "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire",
    },
    {
        heading: "Are the NFTs generated On-Chain?",
        text: "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire",
    },
    {
        heading:
            "Are there any limitations to the types of NFTs that can be generated?",
        text: "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire",
    },
    {
        heading: "What are the legal terms on the NFTs generated by Cryptoverse",
        text: "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire",
    },
];
export const StyleList = [
    {
        label:"Realistic",
        value:"photographic"
    },
    {
        label:"Digital Art",
        value:"digital-art"
    },
    {
        label:"Cartoon",
        value:"comic-book"
    },
    {
        label:"3D Model",
        value:"3d-model"
    },
    {
        label:"Pixel Art",
        value:"pixel-art"
    },
    {
        label:"Anime",
        value:"anime"
    },
];

export const ImageAspectRatio = ["AR  1:1", "AR  2:3", "AR  3:2"];
export const UpscaleList = ["Original (1024x1024)", "x2 (2048x2048)"]


export const ImageQuantity = [
    {
        heading: "Single NFT Image",
        title: "",
    },
    {
        heading: "Multi-NFT Collection",
        title: "1-10 Images",
    },
]

export const ImageArtVersion = [
    {
        heading: "Visionary Forge",
        title: "",
    },
    {
        heading: "Draw Dreamer",
        title: "Generation2",
    },
    {
        heading: "Anime Verse",
        title: "Generation2",
    },
    {
        heading: "Real Version",
        title: "Generation2",
    },
    {
        heading: "Fantasy Verse",
        title: "Generation2",
    },
]