name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          # Connect to DigitalOcean Droplet
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
            echo "Connected to server"

            # Navigate to the project directory
            cd ~/crypto-verse

            # Reset any uncommitted changes
            git reset --hard

            # Ensure we are on the main branch and pull the latest changes
            git checkout main
          
            echo "Deployment successful!"
          EOF
