name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          # Connect to server and deploy
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
            echo "Connected to server"
            
            # Navigate to the project directory
            cd ~/crypto-verse

            # Pull the latest changes from the main branch
            git checkout main  # Ensure we are on the main branch
            git pull origin main

            # Install dependencies
            npm install

            # Build the project
            npm run build

            # Restart PM2 processes
            pm2 restart all

            echo "Deployment successful!"
          EOF
