name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          # Connect to server and deploy
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
            echo "Connected to server"

            # Navigate to the project directory
            cd ~/crypto-verse

            # Ensure we are on the main branch and pull changes
            git checkout main
            git pull origin main

            # Install npm (Node.js package manager) if not installed
            if ! command -v npm &> /dev/null
            then
              echo "npm could not be found, installing..."
              curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
              sudo apt-get install -y nodejs
            fi

            # Install pm2 if not installed
            if ! command -v pm2 &> /dev/null
            then
              echo "pm2 could not be found, installing..."
              sudo npm install pm2@latest -g
            fi

            # Install dependencies
            npm install

            # Build the project
            npm run build

            # Restart PM2 processes
            pm2 restart all

            echo "Deployment successful!"
          EOF
